START {
  recover cmd="/usr/sbin/cyrus ctl_cyrusdb -r"
}

SERVICES {
  imap cmd="imapd" listen="127.0.0.1:1143" prefork=0 maxchild=20
  lmtpunix cmd="lmtpd" listen="/tmp/worldfixture-mail/run/lmtp" prefork=0 maxchild=20
}

EVENTS {
  checkpoint cmd="/usr/sbin/cyrus ctl_cyrusdb -c" period=30
}
