import { normalizeId } from "./domain.mjs";

export const NOTION_ADMIN_VERSION = "2026-06-01";
const DEFAULT_TIME = "2026-09-03T09:00:00.000Z";

function col(store, name, indexes) { return store.collection(name, indexes); }
function currentTime(store) { return Date.parse(store.getData("notion_clock") ?? DEFAULT_TIME); }
function isoTime(store) { return new Date(currentTime(store)).toISOString(); }
function nextId(store, kind, prefix) { const key = `notion_admin_counter_${kind}`; const value = (store.getData(key) ?? 0) + 1; store.setData(key, value); return `${prefix}-0000-4000-8000-${String(value).padStart(12, "0")}`; }
function error(c, status, code, message) { return c.json({ object: "error", code, status, message }, status); }
async function json(c) { try { return await c.req.json(); } catch { return null; } }

function guard(c, store, scope, spaceId = null) {
  if (!c.get("authUser")) return { response: error(c, 401, "unauthorized", "Unauthorized.") };
  if (c.req.header("Notion-Version") !== NOTION_ADMIN_VERSION) return { response: error(c, 400, "validation_error", `Notion-Version must be ${NOTION_ADMIN_VERSION}.`) };
  const scopes = c.get("authScopes") ?? [];
  if (!scopes.includes(scope)) return { response: error(c, 403, "restricted_resource", `The organization token requires ${scope}.`) };
  const workspace = store.getData("notion_workspace") ?? {};
  if (spaceId !== null && String(spaceId) !== String(workspace.id)) return { response: error(c, 404, "object_not_found", "Workspace not found.") };
  const actor = col(store, "notion_users", ["notion_id", "email"]).findOneBy("email", c.get("authUser").login);
  return { actor, workspace };
}

function size(c) { const value = c.req.query("page_size") === undefined ? 100 : Number(c.req.query("page_size")); return Number.isInteger(value) && value >= 1 && value <= 100 ? value : null; }
function page(records, cursor, limit) {
  const start = cursor ? records.findIndex((item) => (item.notion_id ?? item.id) === cursor) + 1 : 0;
  if (cursor && start === 0) return { invalid: true };
  const results = records.slice(start, start + limit); const more = start + limit < records.length;
  return { results, has_more: more, next_cursor: more ? results.at(-1)?.notion_id ?? results.at(-1)?.id ?? null : null };
}
function list(c, records, type, map = (item) => item) {
  const limit = size(c); if (limit === null) return error(c, 400, "validation_error", "page_size must be from 1 through 100.");
  const selected = page(records, c.req.query("start_cursor"), limit); if (selected.invalid) return error(c, 400, "validation_error", "start_cursor is not valid.");
  return c.json({ object: "list", type, results: selected.results.map(map), has_more: selected.has_more, next_cursor: selected.next_cursor });
}
// The same two guards `list` and `plainList` apply, for the two routes whose
// response envelope is neither of theirs.
//
// `size(c)` returns `null` to mean "page_size is invalid", and both of those
// routes wrote `size(c) ?? 100` -- turning the refusal into a silent hundred. And
// neither checked `page`'s `invalid` flag, so an unknown `start_cursor` reached
// `.map()` on an undefined `results`. Both measured against a running fixture:
// `GET /admin/v1/legal_holds?page_size=0` answered 200, and
// `?start_cursor=totally-bogus` answered 500 `Cannot read properties of
// undefined (reading 'map')`. Every sibling admin list answers 400 for both.
function paged(c, records) {
  const limit = size(c);
  if (limit === null) return { response: error(c, 400, "validation_error", "page_size must be from 1 through 100.") };
  const selected = page(records, c.req.query("start_cursor"), limit);
  if (selected.invalid) return { response: error(c, 400, "validation_error", "start_cursor is not valid.") };
  return { selected };
}
function plainList(c, records, map = (item) => item) {
  const limit = size(c); if (limit === null) return error(c, 400, "validation_error", "page_size must be from 1 through 100.");
  const selected = page(records, c.req.query("start_cursor"), limit); if (selected.invalid) return error(c, 400, "validation_error", "start_cursor is not valid.");
  return c.json({ results: selected.results.map(map), has_more: selected.has_more, ...(selected.next_cursor ? { next_cursor: selected.next_cursor } : {}) });
}
function legalHold(record) {
  return { id: record.notion_id, created_by: record.created_by, created_time: record.created_time, start_date: record.start_date, status: record.status, user_interaction_type: [...record.user_interaction_type], users: { ids: [...record.user_ids], total: record.user_ids.length }, workspaces: { ids: [...record.workspace_ids], total: record.workspace_ids.length }, ...(record.name ? { name: record.name } : {}), ...(record.description ? { description: record.description } : {}), ...(record.icon ? { icon: record.icon } : {}), ...(record.end_date ? { end_date: record.end_date } : {}) };
}
function group(record) { return { object: "group", id: record.notion_id, name: record.name }; }
function membership(record) { return { object: "group_membership", group_id: record.group_id, member: { type: "user", user_id: record.user_id }, role: record.role }; }
function adminUser(record) { return record.type === "bot" ? { object: "user", id: record.notion_id, name: record.name ?? null, avatar_url: record.avatar_url ?? null, type: "bot", bot: {} } : { object: "user", id: record.notion_id, name: record.name ?? null, avatar_url: record.avatar_url ?? null, type: "person", person: { email: record.email } }; }

function adminAgent(record, spaceId) {
  const status = record.status === "disabled" ? record.pause_reason ?? "disabled_from_api" : record.status;
  return { alive: record.status !== "deleted", id: record.notion_id, space_id: spaceId, status, type: record.agent_type === "autofill_custom_agent" ? "database_autofill" : "custom", created_by_id: record.created_by, created_by_table: "notion_user", created_time: Date.parse(record.created_time), description: record.description ?? "", last_edited_by_id: record.created_by, last_edited_by_table: "notion_user", last_edited_time: Date.parse(record.last_edited_time), name: record.name, parent_id: spaceId, parent_table: "space", modules: (record.connections ?? []).map((item, index) => ({ id: `${record.notion_id}:${index}`, type: item.type, name: item.name })), ...(record.last_run_at ? { last_run_time: Date.parse(record.last_run_at) } : {}), ...(record.model?.mode === "pinned" && record.model.id ? { model: record.model.id } : {}), ...(record.deleted_at ? { moved_to_trash_time: Date.parse(record.deleted_at) } : {}) };
}

function creditUsage(record) {
  return { id: record.notion_id, name: record.name, type: record.agent_type === "autofill_custom_agent" ? "database_autofill" : "custom", status: record.status === "disabled" ? record.pause_reason ?? "disabled_from_api" : record.status, created_by_id: record.created_by, ...(record.credit_limit !== null && record.credit_limit !== undefined ? { credit_limit: record.credit_limit } : {}), credit_per_billing_period_list: [], total_credits_used: record.total_credits_used ?? 0, runs_completed: record.runs_completed ?? 0 };
}

export function registerAdminApiRoutes(app, store) {
  const holds = col(store, "notion_admin_legal_holds", ["notion_id", "status"]);
  const exports = col(store, "notion_admin_exports", ["notion_id", "space_id", "status"]);
  const groups = col(store, "notion_admin_groups", ["notion_id", "space_id", "name"]);
  const members = col(store, "notion_admin_group_members", ["notion_id", "group_id", "user_id"]);
  const mcpConnections = col(store, "notion_admin_mcp_connections", ["notion_id", "client_key", "user_id", "workspace_id"]);
  const pats = col(store, "notion_admin_personal_access_tokens", ["notion_id", "space_id", "status"]);
  const permissions = col(store, "notion_admin_agent_permissions", ["notion_id", "space_id", "agent_id"]);
  const agents = col(store, "notion_agents", ["notion_id", "created_by", "status"]);
  const users = col(store, "notion_users", ["notion_id", "email"]);
  const pages = col(store, "notion_pages", ["notion_id"]);

  const findHold = (id) => holds.findOneBy("notion_id", id);
  const findGroup = (id, space) => { const result = groups.findOneBy("notion_id", id); return result?.space_id === space ? result : null; };
  const findAgent = (id) => agents.findOneBy("notion_id", normalizeId(id));

  app.get("/admin/v1/legal_holds", (c) => { const auth = guard(c, store, "legal-hold:read"); if (auth.response) return auth.response; const { response, selected } = paged(c, holds.all()); if (response) return response; return c.json({ legal_holds: selected.results.map(legalHold), ...(selected.next_cursor ? { next_cursor: selected.next_cursor } : {}) }); });
  app.post("/admin/v1/legal_holds", async (c) => {
    const auth = guard(c, store, "legal-hold:write"); if (auth.response) return auth.response; const input = await json(c);
    if (!input?.name || typeof input.start_date !== "number" || !Array.isArray(input.user_ids) || !Array.isArray(input.user_interaction_type) || input.user_interaction_type.some((value) => !["page.created", "page.edited", "page.viewed"].includes(value))) return error(c, 400, "validation_error", "The request body is invalid.");
    if (input.user_ids.some((id) => !users.findOneBy("notion_id", normalizeId(id)))) return error(c, 404, "object_not_found", "A user was not found.");
    const record = holds.insert({ notion_id: nextId(store, "legal_hold", "d1000000"), created_by: auth.actor?.notion_id, created_time: currentTime(store), start_date: input.start_date, end_date: input.end_date ?? null, status: "active", user_interaction_type: [...new Set(input.user_interaction_type)], user_ids: [...new Set(input.user_ids.map(normalizeId))], workspace_ids: [String(auth.workspace.id)], name: input.name, description: input.description ?? null, icon: input.icon ?? null });
    return c.json(legalHold(record));
  });
  app.get("/admin/v1/legal_holds/:id", (c) => { const auth = guard(c, store, "legal-hold:read"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); return record ? c.json(legalHold(record)) : error(c, 404, "object_not_found", "Legal hold not found."); });
  app.patch("/admin/v1/legal_holds/:id", async (c) => { const auth = guard(c, store, "legal-hold:write"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); if (!input || !["name", "description", "icon"].some((key) => input[key] !== undefined)) return error(c, 400, "validation_error", "The request body is invalid."); return c.json(legalHold(holds.update(record.id, { ...(input.name !== undefined ? { name: input.name } : {}), ...(input.description !== undefined ? { description: input.description } : {}), ...(input.icon !== undefined ? { icon: input.icon } : {}) }))); });
  app.post("/admin/v1/legal_holds/:id/export", (c) => { const auth = guard(c, store, "legal-hold:export"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); return record ? c.json({ legal_hold_export_id: nextId(store, "legal_hold_export", "d2000000") }) : error(c, 404, "object_not_found", "Legal hold not found."); });
  app.post("/admin/v1/legal_holds/:id/release", (c) => { const auth = guard(c, store, "legal-hold:write-high-impact"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); return c.json(legalHold(holds.update(record.id, { status: "released", end_date: currentTime(store) }))); });
  app.get("/admin/v1/legal_holds/:id/users", (c) => { const auth = guard(c, store, "legal-hold:read"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); const { response, selected } = paged(c, record.user_ids.map((id) => ({ id }))); if (response) return response; return c.json({ user_ids: selected.results.map((item) => item.id), ...(selected.next_cursor ? { next_cursor: selected.next_cursor } : {}) }); });
  app.post("/admin/v1/legal_holds/:id/users", async (c) => { const auth = guard(c, store, "legal-hold:write"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); if (!Array.isArray(input?.user_ids) || input.user_ids.some((id) => !users.findOneBy("notion_id", normalizeId(id)))) return error(c, 400, "validation_error", "user_ids is invalid."); return c.json(legalHold(holds.update(record.id, { user_ids: [...new Set([...record.user_ids, ...input.user_ids.map(normalizeId)])] }))); });
  app.delete("/admin/v1/legal_holds/:id/users/:user_id", (c) => { const auth = guard(c, store, "legal-hold:write"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); return c.json(legalHold(holds.update(record.id, { user_ids: record.user_ids.filter((id) => id !== normalizeId(c.req.param("user_id"))) }))); });
  app.get("/admin/v1/legal_holds/:id/workspaces", (c) => { const auth = guard(c, store, "legal-hold:read"); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); return record ? c.json({ workspace_ids: [...record.workspace_ids] }) : error(c, 404, "object_not_found", "Legal hold not found."); });
  app.get("/admin/v1/legal_holds/:id/spaces/:space_id/pages", (c) => { const auth = guard(c, store, "legal-hold:read", c.req.param("space_id")); if (auth.response) return auth.response; const record = findHold(c.req.param("id")); if (!record) return error(c, 404, "object_not_found", "Legal hold not found."); const ids = pages.all().filter((item) => record.user_ids.includes(item.created_by)).map((item) => item.notion_id); return c.json({ page_ids: ids }); });

  app.post("/admin/v1/spaces/:space_id/exports", async (c) => { const auth = guard(c, store, "workspace:export", c.req.param("space_id")); if (auth.response) return auth.response; const input = await json(c); if (!input || !["html", "markdown", "pdf"].includes(input.export_type) || typeof input.on_behalf_of_user_email !== "string") return error(c, 400, "validation_error", "The request body is invalid."); if (!users.findOneBy("email", input.on_behalf_of_user_email)) return error(c, 404, "object_not_found", "User not found."); const id = nextId(store, "export", "d3000000"); exports.insert({ notion_id: id, space_id: c.req.param("space_id"), status: "completed", export_type: "space", export_format: input.export_type, pages_exported: pages.count(), created_time: currentTime(store), last_edited_time: currentTime(store), download_urls: [] }); return c.json({ export_job_id: id, status: "enqueued" }); });
  app.get("/admin/v1/spaces/:space_id/exports/:export_id", (c) => { const auth = guard(c, store, "workspace:export", c.req.param("space_id")); if (auth.response) return auth.response; const record = exports.findOneBy("notion_id", c.req.param("export_id")); if (!record || record.space_id !== c.req.param("space_id")) return error(c, 404, "object_not_found", "Export not found."); return c.json({ export_job_id: record.notion_id, status: record.status, export_type: record.export_type, export_format: record.export_format, pages_exported: record.pages_exported, created_time: record.created_time, last_edited_time: record.last_edited_time, ...(record.download_urls?.length ? { download_urls: record.download_urls } : {}) }); });
  app.post("/admin/v1/managed_users/revoke_session", async (c) => { const auth = guard(c, store, "managed-user-session:write"); if (auth.response) return auth.response; const input = await json(c); const user = input?.user?.type === "email" ? users.findOneBy("email", input.user.email) : input?.user?.type === "id" ? users.findOneBy("notion_id", normalizeId(input.user.id)) : null; return user ? c.json({ status: "revoked" }) : error(c, 404, "object_not_found", "Managed user not found."); });

  app.get("/admin/v1/mcp_client_connections", (c) => { const auth = guard(c, store, "mcp-client-connection:read"); if (auth.response) return auth.response; let records = mcpConnections.all(); if (c.req.query("user_id")) records = records.filter((item) => item.user_id === normalizeId(c.req.query("user_id"))); if (c.req.query("workspace_id")) records = records.filter((item) => item.workspace_id === c.req.query("workspace_id")); return plainList(c, records, (item) => ({ client: { key: item.client_key, name: item.client_name, type: item.client_type ?? "other" }, created_at: item.connected_at, is_enterprise_managed: Boolean(item.is_enterprise_managed), user: { id: item.user_id }, workspaces: [{ id: item.workspace_id }], ...(item.last_active_at ? { last_active_at: item.last_active_at } : {}), ...(item.idp_issuer ? { idp_issuer: item.idp_issuer } : {}) })); });
  app.post("/admin/v1/mcp_client_connections/revoke", async (c) => { const auth = guard(c, store, "mcp-client-connection:write-high-impact"); if (auth.response) return auth.response; const input = await json(c); if (!input?.client_key || !input.user_id || !input.workspace_id) return error(c, 400, "validation_error", "The request body is invalid."); let count = 0; for (const item of mcpConnections.all().filter((entry) => entry.client_key === input.client_key && entry.user_id === normalizeId(input.user_id) && entry.workspace_id === input.workspace_id && !entry.revoked)) { mcpConnections.update(item.id, { revoked: true, revoked_at: currentTime(store) }); count += 1; } return c.json({ revoked_token_count: count }); });
  app.put("/admin/v1/mcp_client_connections/enterprise_managed_access", async (c) => { const auth = guard(c, store, "mcp-client-connection:write-high-impact"); if (auth.response) return auth.response; const input = await json(c); if (!["allowed", "denied"].includes(input?.access) || !input.user_id || !input.workspace_id) return error(c, 400, "validation_error", "The request body is invalid."); let count = 0; for (const item of mcpConnections.all().filter((entry) => entry.user_id === normalizeId(input.user_id) && entry.workspace_id === input.workspace_id && entry.is_enterprise_managed)) { mcpConnections.update(item.id, { enterprise_managed_access: input.access, ...(input.access === "denied" ? { revoked: true } : {}) }); if (input.access === "denied") count += 1; } return c.json({ access: input.access, revoked_token_count: count }); });

  app.get("/admin/v1/spaces/:space_id/users", (c) => { const auth = guard(c, store, "user:read", c.req.param("space_id")); if (auth.response) return auth.response; return list(c, users.all(), "user", adminUser); });
  app.get("/admin/v1/spaces/:space_id/groups", (c) => { const auth = guard(c, store, "permission-group:read", c.req.param("space_id")); if (auth.response) return auth.response; return list(c, groups.all().filter((item) => item.space_id === c.req.param("space_id") && !item.deleted), "group", group); });
  app.post("/admin/v1/spaces/:space_id/groups", async (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const input = await json(c); if (typeof input?.name !== "string" || !input.name.trim() || input.name.length > 200) return error(c, 400, "validation_error", "name is invalid."); const record = groups.insert({ notion_id: nextId(store, "group", "d4000000"), space_id: c.req.param("space_id"), name: input.name }); return c.json(group(record)); });
  app.get("/admin/v1/spaces/:space_id/groups/:group_id", (c) => { const auth = guard(c, store, "permission-group:read", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); return record && !record.deleted ? c.json(group(record)) : error(c, 404, "object_not_found", "Group not found."); });
  app.patch("/admin/v1/spaces/:space_id/groups/:group_id", async (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Group not found."); if (typeof input?.name !== "string" || !input.name.trim()) return error(c, 400, "validation_error", "name is invalid."); return c.json(group(groups.update(record.id, { name: input.name }))); });
  app.delete("/admin/v1/spaces/:space_id/groups/:group_id", (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); if (!record) return error(c, 404, "object_not_found", "Group not found."); groups.update(record.id, { deleted: true }); return c.json(group(record)); });
  app.get("/admin/v1/spaces/:space_id/groups/:group_id/members", (c) => { const auth = guard(c, store, "permission-group:read", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); if (!record) return error(c, 404, "object_not_found", "Group not found."); return list(c, members.findBy("group_id", record.notion_id), "group_membership", membership); });
  app.post("/admin/v1/spaces/:space_id/groups/:group_id/members", async (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Group not found."); if (input?.member?.type !== "user" || !users.findOneBy("notion_id", normalizeId(input.member.user_id)) || !["owner", "member"].includes(input.role)) return error(c, 400, "validation_error", "The membership is invalid."); if (members.findBy("group_id", record.notion_id).some((item) => item.user_id === normalizeId(input.member.user_id))) return error(c, 409, "conflict_error", "The user is already a direct member."); return c.json(membership(members.insert({ notion_id: nextId(store, "group_member", "d5000000"), group_id: record.notion_id, user_id: normalizeId(input.member.user_id), role: input.role }))); });
  app.patch("/admin/v1/spaces/:space_id/groups/:group_id/members/users/:user_id", async (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); const member = record && members.findBy("group_id", record.notion_id).find((item) => item.user_id === normalizeId(c.req.param("user_id"))); const input = await json(c); if (!member) return error(c, 404, "object_not_found", "Group member not found."); if (!["owner", "member"].includes(input?.role)) return error(c, 400, "validation_error", "role is invalid."); return c.json(membership(members.update(member.id, { role: input.role }))); });
  app.delete("/admin/v1/spaces/:space_id/groups/:group_id/members/users/:user_id", (c) => { const auth = guard(c, store, "permission-group:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findGroup(c.req.param("group_id"), c.req.param("space_id")); const member = record && members.findBy("group_id", record.notion_id).find((item) => item.user_id === normalizeId(c.req.param("user_id"))); if (!member) return error(c, 404, "object_not_found", "Group member not found."); members.delete(member.id); return c.json(membership(member)); });

  app.get("/admin/v1/spaces/:space_id/personal_access_tokens", (c) => { const auth = guard(c, store, "personal-access-token:read", c.req.param("space_id")); if (auth.response) return auth.response; let records = pats.all().filter((item) => item.space_id === c.req.param("space_id")); if (c.req.query("status")) records = records.filter((item) => item.status === c.req.query("status")); if (c.req.query("query")) records = records.filter((item) => item.name?.toLowerCase().includes(c.req.query("query").toLowerCase())); return plainList(c, records, (item) => ({ id: item.notion_id, creator: structuredClone(item.creator), created_at: item.token_created_at, status: item.status, ...(item.name ? { name: item.name } : {}), ...(item.expires_at ? { expires_at: item.expires_at } : {}), ...(item.last_used_at ? { last_used_at: item.last_used_at } : {}), ...(item.revoked_at ? { revoked_at: item.revoked_at, revoked_by: structuredClone(item.revoked_by) } : {}) })); });
  app.delete("/admin/v1/spaces/:space_id/personal_access_tokens/:bot_id", (c) => { const auth = guard(c, store, "personal-access-token:write-high-impact", c.req.param("space_id")); if (auth.response) return auth.response; const record = pats.findOneBy("notion_id", normalizeId(c.req.param("bot_id"))); if (!record || record.space_id !== c.req.param("space_id")) return error(c, 404, "object_not_found", "Personal access token not found."); pats.update(record.id, { status: "revoked", revoked_at: currentTime(store), revoked_by: { type: "organization_bot", id: auth.actor?.notion_id } }); return c.json({}); });

  app.get("/admin/v1/spaces/:space_id/agents", (c) => { const auth = guard(c, store, "workflows:read", c.req.param("space_id")); if (auth.response) return auth.response; let records = agents.all().filter((item) => item.status !== "deleted"); if (c.req.query("query")) records = records.filter((item) => item.name.toLowerCase().includes(c.req.query("query").toLowerCase())); return plainList(c, records, (record) => adminAgent(record, c.req.param("space_id"))); });
  app.get("/admin/v1/spaces/:space_id/agents/:agent_id/credit_usage", (c) => { const auth = guard(c, store, "workflows:read", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); if (!record) return error(c, 404, "object_not_found", "Agent not found."); return c.json({ ...creditUsage(record), has_more: false }); });
  app.get("/admin/v1/spaces/:space_id/agents/credit_usage", (c) => { const auth = guard(c, store, "workflows:read", c.req.param("space_id")); if (auth.response) return auth.response; return plainList(c, agents.all(), (record) => ({ ...creditUsage(record), has_more: false })); });
  app.put("/admin/v1/spaces/:space_id/agents/:agent_id/credit_limit", async (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Agent not found."); if (input?.credit_limit !== null && (!Number.isInteger(input?.credit_limit) || input.credit_limit < 0)) return error(c, 400, "validation_error", "credit_limit is invalid."); agents.update(record.id, { credit_limit: input.credit_limit, last_edited_time: isoTime(store) }); return c.json({ credit_limit_by_workspace_admin: input.credit_limit, enforced_credit_limit: input.credit_limit, current_credit_usage: record.total_credits_used ?? 0, did_clear_paused_state: false, is_active: record.status === "active" }); });
  app.patch("/admin/v1/spaces/:space_id/agents/:agent_id/status", async (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Agent not found."); if (!["active", "disabled"].includes(input?.admin_status)) return error(c, 400, "validation_error", "admin_status is invalid."); const pause = input.admin_status === "disabled" ? "disabled_from_workspace_settings" : null; agents.update(record.id, { status: input.admin_status, pause_reason: pause, last_edited_time: isoTime(store) }); return c.json({ admin_status: input.admin_status, run_status: input.admin_status === "active" ? "running" : "paused", paused_reason: pause }); });
  app.delete("/admin/v1/spaces/:space_id/agents/:agent_id", (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); if (!record) return error(c, 404, "object_not_found", "Agent not found."); agents.update(record.id, { status: "deleted", deleted_at: isoTime(store) }); return c.json({}); });
  app.get("/admin/v1/spaces/:space_id/agents/:agent_id/permissions", (c) => { const auth = guard(c, store, "workflows:read", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); if (!record) return error(c, 404, "object_not_found", "Agent not found."); const value = permissions.findOneBy("agent_id", record.notion_id); return c.json({ permissions: structuredClone(value?.permissions ?? []) }); });
  app.patch("/admin/v1/spaces/:space_id/agents/:agent_id/permissions", async (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const record = findAgent(c.req.param("agent_id")); const input = await json(c); if (!record) return error(c, 404, "object_not_found", "Agent not found."); if (!input || input.set !== undefined && !Array.isArray(input.set) || input.remove !== undefined && !Array.isArray(input.remove)) return error(c, 400, "validation_error", "The request body is invalid."); let value = permissions.findOneBy("agent_id", record.notion_id); if (!value) value = permissions.insert({ notion_id: nextId(store, "agent_permission", "d6000000"), space_id: c.req.param("space_id"), agent_id: record.notion_id, permissions: [] }); let result = [...value.permissions]; for (const remove of input.remove ?? []) result = result.filter((item) => JSON.stringify(item.principal) !== JSON.stringify(remove)); for (const set of input.set ?? []) { if (!set?.principal || !["view_and_interact", "edit", "full_access"].includes(set.role)) return error(c, 400, "validation_error", "An agent permission is invalid."); result = result.filter((item) => JSON.stringify(item.principal) !== JSON.stringify(set.principal)); result.push({ principal: structuredClone(set.principal), role: set.role, resolved_role: set.role }); } permissions.update(value.id, { permissions: result }); return c.json({ permissions: result }); });
  app.patch("/admin/v1/spaces/:space_id/agents/creation_policy", async (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const input = await json(c); if (!["all_workspace_members", "disabled", "workspace_owners_only"].includes(input?.policy)) return error(c, 400, "validation_error", "policy is invalid."); store.setData("notion_admin_agent_creation_policy", input.policy); if (input.disable_existing_agents) for (const record of agents.all()) agents.update(record.id, { status: "disabled", pause_reason: "disabled_from_workspace_settings" }); const counts = agents.all().reduce((out, item) => ({ ...out, [item.status]: (out[item.status] ?? 0) + 1 }), { active: 0, disabled: 0, deleted: 0 }); return c.json({ space_id: c.req.param("space_id"), space_name: auth.workspace.name, current_policy: input.policy, current_policy_description: input.policy.replaceAll("_", " "), agent_counts: counts }); });
  app.patch("/admin/v1/spaces/:space_id/credit_limit", async (c) => { const auth = guard(c, store, "workflows:write", c.req.param("space_id")); if (auth.response) return auth.response; const input = await json(c); if (input?.default_agent_credit_limit !== null && (!Number.isInteger(input?.default_agent_credit_limit) || input.default_agent_credit_limit < 0)) return error(c, 400, "validation_error", "default_agent_credit_limit is invalid."); store.setData("notion_admin_default_agent_credit_limit", input.default_agent_credit_limit); return c.json({ space_id: c.req.param("space_id"), default_agent_credit_limit: input.default_agent_credit_limit }); });
}

export function seedNotionAdminApi(store, config = {}) {
  const workspace = config.workspace ?? { id: "worldfixture-notion-workspace" };
  const groups = col(store, "notion_admin_groups", ["notion_id", "space_id", "name"]);
  const members = col(store, "notion_admin_group_members", ["notion_id", "group_id", "user_id"]);
  const connections = col(store, "notion_admin_mcp_connections", ["notion_id", "client_key", "user_id", "workspace_id"]);
  const pats = col(store, "notion_admin_personal_access_tokens", ["notion_id", "space_id", "status"]);
  const permissions = col(store, "notion_admin_agent_permissions", ["notion_id", "space_id", "agent_id"]);
  for (const input of config.admin?.groups ?? []) { groups.insert({ notion_id: normalizeId(input.id), space_id: String(input.space_id ?? workspace.id), name: input.name }); for (const member of input.members ?? []) members.insert({ notion_id: normalizeId(member.id), group_id: normalizeId(input.id), user_id: normalizeId(member.user_id), role: member.role ?? "member" }); }
  for (const input of config.admin?.mcp_client_connections ?? []) connections.insert({ notion_id: normalizeId(input.id), client_key: input.client_key, client_name: input.client_name, client_type: input.client_type ?? "other", connected_at: input.created_at ?? Date.parse(DEFAULT_TIME), is_enterprise_managed: Boolean(input.is_enterprise_managed), user_id: normalizeId(input.user_id), workspace_id: String(input.workspace_id ?? workspace.id), last_active_at: input.last_active_at ?? null, idp_issuer: input.idp_issuer ?? null, enterprise_managed_access: input.enterprise_managed_access ?? "allowed", revoked: Boolean(input.revoked) });
  for (const input of config.admin?.personal_access_tokens ?? []) pats.insert({ notion_id: normalizeId(input.id), space_id: String(input.space_id ?? workspace.id), creator: structuredClone(input.creator), token_created_at: input.created_at ?? Date.parse(DEFAULT_TIME), status: input.status ?? "active", name: input.name ?? null, expires_at: input.expires_at ?? null, last_used_at: input.last_used_at ?? null });
  for (const input of config.agents ?? []) permissions.insert({ notion_id: nextId(store, "agent_permission", "d6000000"), space_id: String(workspace.id), agent_id: normalizeId(input.id), permissions: (input.accessible_by ?? []).map((userId) => ({ principal: { type: "user", user_id: normalizeId(userId) }, role: (input.editable_by ?? []).map(normalizeId).includes(normalizeId(userId)) ? "full_access" : "view_and_interact", resolved_role: (input.editable_by ?? []).map(normalizeId).includes(normalizeId(userId)) ? "full_access" : "view_and_interact" })) });
}
