export const NOTION_MCP_SNAPSHOT = "2026-09-03";
export const NOTION_MCP_PROTOCOL_VERSION = "2025-11-25";

const dateRange = {
  type: "object",
  properties: {
    start_date: { type: "string", format: "date" },
    end_date: { type: "string", format: "date" },
  },
  additionalProperties: false,
};

const parent = {
  type: "object",
  description: "A page, data source, database, or workspace parent understood by the WorldFixture Notion domain.",
  properties: {
    page_id: { type: "string" },
    data_source_id: { type: "string" },
    database_id: { type: "string" },
    workspace: { type: "boolean" },
  },
  additionalProperties: false,
};

const viewTypes = ["table", "board", "list", "calendar", "timeline", "gallery", "form", "chart", "map", "dashboard"];

const writeAnnotations = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
const updateAnnotations = { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false };

export const notionMcpTools = [
  {
    name: "notion-search",
    title: "Search Notion and connected sources",
    description: "Search accessible Notion content or workspace users. Fetch important matches before relying on them.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search text. It can be omitted for a filters-only internal search." },
        filters: {
          type: "object",
          properties: {
            created_date_range: dateRange,
            created_by_user_ids: { type: "array", items: { type: "string" } },
            last_edited_date_range: dateRange,
            last_edited_by_user_ids: { type: "array", items: { type: "string" } },
            title_only: { type: "boolean" },
            in_trash: { type: "boolean" },
            content_status: { type: "string", enum: ["verified", "expired", "none"] },
          },
          additionalProperties: false,
        },
        page_url: { type: "string", description: "Page URL or ID that limits the search to that page subtree." },
        page_size: { type: "integer", minimum: 1, maximum: 50, default: 10 },
        query_type: { type: "string", enum: ["internal", "user"], default: "internal" },
        teamspace_id: { type: "string" },
        data_source_url: { type: "string", description: "A collection:// data-source URL." },
        content_search_mode: { type: "string", enum: ["workspace_search", "ai_search"] },
        max_highlight_length: { type: "integer", minimum: 0, default: 200 },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-fetch",
    title: "Fetch Notion content",
    description: "Fetch a page, database, data source, saved view, block subtree, or the connected identity by URL or ID.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", minLength: 1 },
        include_transcript: { type: "boolean", default: false },
        include_discussions: { type: "boolean", default: false },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-search-skills",
    title: "Search Notion Skills",
    description: "Search accessible pages that are marked as reusable Skills.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        teamspace_id: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 10 },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-convert-page-to-skill",
    title: "Convert a Notion page to a Skill",
    description: "Mark one accessible page as a reusable Skill and add an optional Skill description.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: { page_id: { type: "string", minLength: 1 }, description: { type: "string" } },
      required: ["page_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-file-upload",
    title: "Create a Notion file upload URL",
    description: "Create a short-lived URL for one multipart upload of a local file of at most 20 MiB.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        filename: { type: "string", minLength: 1, description: "File name, including its extension." },
        content_type: { type: "string", minLength: 1, description: "Optional MIME type for the file." },
      },
      required: ["filename"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-attachment",
    title: "Create a Notion attachment",
    description: "Create an attachment from UTF-8 text, one direct public HTTPS URL, or one completed file upload from this integration.",
    annotations: { ...writeAnnotations, openWorldHint: true },
    inputSchema: {
      type: "object",
      properties: {
        filename: { type: "string", minLength: 1 },
        content_type: { type: "string", minLength: 1 },
        content: { type: "string", description: "UTF-8 text content of at most 200 KiB." },
        source_url: { type: "string", minLength: 1, description: "Direct public HTTPS URL that does not redirect." },
        source_file_id: { type: "string", minLength: 1, description: "Completed file upload created by this integration." },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-download-attachment",
    title: "Download a Notion text attachment",
    description: "Download at most 200 KiB of UTF-8 text from an attachment created by notion-create-attachment.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: { file_upload_id: { type: "string", minLength: 1 } },
      required: ["file_upload_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-pages",
    title: "Create Notion pages",
    description: "Create one or more pages. This behavioral preview does not claim exact hosted Notion MCP schema parity.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        parent,
        creation_mode: { type: "string", enum: ["draft"] },
        pages: {
          type: "array",
          minItems: 1,
          items: {
            type: "object",
            properties: {
              properties: { type: "object", additionalProperties: true },
              title: { type: "string" },
              content: { type: "string" },
              template_id: { type: "string" },
              icon: {},
              cover: {},
              position: { type: "object", additionalProperties: true },
              is_skill: { type: "boolean" },
            },
            additionalProperties: false,
          },
        },
        allow_async: { type: "boolean", default: false },
      },
      required: ["pages"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-update-page",
    title: "Update a Notion page",
    description: "Update page properties, content, template, icon, cover, or Skill state.",
    annotations: updateAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        page_id: { type: "string", minLength: 1 },
        command: { type: "string", enum: ["update_properties", "update_content", "replace_content", "insert_content", "apply_template", "update_verification"] },
        properties: { type: "object", additionalProperties: true },
        content: { type: "string" },
        new_str: { type: "string" },
        content_updates: { type: "array", items: { type: "object", additionalProperties: true } },
        position: { type: "object", additionalProperties: true },
        allow_deleting_content: { type: "boolean" },
        template_id: { type: "string" },
        erase_content: { type: "boolean" },
        icon: {},
        cover: {},
        is_skill: { type: "boolean" },
        verification_status: { type: "string", enum: ["verified", "unverified"] },
        verification_expiry_days: { type: "integer", minimum: 1 },
        allow_async: { type: "boolean", default: false },
      },
      required: ["page_id", "command"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-move-pages",
    title: "Move Notion pages",
    description: "Move one or more pages or databases to a new parent.",
    annotations: updateAnnotations,
    inputSchema: {
      type: "object",
      properties: { page_or_database_ids: { type: "array", minItems: 1, maxItems: 100, items: { type: "string" } }, new_parent: parent },
      required: ["page_or_database_ids", "new_parent"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-duplicate-page",
    title: "Duplicate a Notion page",
    description: "Start an asynchronous page duplication task.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: { page_id: { type: "string", minLength: 1 }, parent },
      required: ["page_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-database",
    title: "Create a Notion database",
    description: "Create a database, its initial data source, and its initial view.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        parent,
        title: { type: "string", minLength: 1 },
        description: { type: "string" },
        properties: { type: "object", additionalProperties: true },
        schema: { type: "string", description: "Optional compact schema DSL accepted by the domain." },
        database_type: { type: "string" },
      },
      required: ["title"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-folder",
    title: "Create a Notion folder",
    description: "Create an empty folder under a page.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: { parent, title: { type: "string", minLength: 1 } },
      required: ["parent", "title"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-update-data-source",
    title: "Update a Notion data source",
    description: "Update a data source name, description, properties, or parent.",
    annotations: updateAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        data_source_id: { type: "string", minLength: 1 },
        name: { type: "string" },
        description: { type: "string" },
        properties: { type: "object", additionalProperties: true },
        parent,
      },
      required: ["data_source_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-create-view",
    title: "Create a Notion database view",
    description: "Create a saved view with optional filter, sort, and display configuration.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        data_source_id: { type: "string", minLength: 1 },
        name: { type: "string", minLength: 1 },
        type: { type: "string", enum: viewTypes },
        filter: {},
        sorts: { type: "array", items: {} },
        configuration: { type: "object", additionalProperties: true },
      },
      required: ["data_source_id", "name"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-update-view",
    title: "Update a Notion database view",
    description: "Update only the supplied view name, filter, sorts, or display configuration.",
    annotations: updateAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        view_id: { type: "string", minLength: 1 },
        name: { type: "string" },
        filter: {},
        sorts: { type: "array", items: {} },
        configuration: { type: "object", additionalProperties: true },
      },
      required: ["view_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-query-data-sources",
    title: "Query Notion data sources",
    description: "Read rows from one data source, run a saved view, or run a scoped SQL-style query.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        mode: { type: "string", enum: ["rows", "view", "sql"] },
        data_source_url: { type: "string" },
        data_source_urls: { type: "array", minItems: 1, items: { type: "string" } },
        view_url: { type: "string" },
        query: { type: "string" },
        filter: {},
        sorts: { type: "array", items: {} },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 50 },
      },
      required: ["mode"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-query-meeting-notes",
    title: "Query Notion meeting notes",
    description: "Query meeting notes where the connected user is an attendee. Supports the current Notion meeting-note filter and sort objects.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        filter: {},
        sort: { type: "array", items: {}, maxItems: 100 },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 50 },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-get-teams",
    title: "Get Notion teams",
    description: "List teamspaces in the current workspace and show whether the connected user is a member.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: { query: { type: "string" }, team_id: { type: "string", minLength: 1 } },
      additionalProperties: false,
    },
  },
  {
    name: "notion-get-users",
    title: "Get Notion users",
    description: "List workspace users or find them by name, email address, or user ID.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: { query: { type: "string" }, user_id: { type: "string", minLength: 1 }, start_cursor: { type: "string" }, page_size: { type: "integer", minimum: 1, maximum: 100, default: 100 } },
      additionalProperties: false,
    },
  },
  {
    name: "notion-get-self",
    title: "Get Notion connection identity",
    description: "Get the connected user, workspace, and workspace file upload limit.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "notion-list-agents",
    title: "List Notion Custom Agents",
    description: "List published Custom Agents that the connected user can access.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string" },
        agent_type: { type: "array", items: { type: "string", enum: ["notion_ai", "custom_agent", "autofill_custom_agent", "external"] } },
        agent_ids: { type: "array", items: { type: "string" } },
        created_by: { type: "array", items: { type: "string" } },
        start_cursor: { type: "string" },
        page_size: { type: "integer", minimum: 1, maximum: 100, default: 100 },
        verbose: { type: "boolean", default: false },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-search-agents",
    title: "Search Notion Custom Agents",
    description: "Search agents by name or description, or browse favorites and workspace agents.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        scope: { type: "string", enum: ["favorites", "workspace"] },
        query: { type: "string" },
        cursor: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 200, default: 20 },
      },
      required: ["scope"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-query-sessions",
    title: "Query Notion agent sessions",
    description: "List accessible Custom Agent sessions with filters, title search, sorting, and cursor pagination.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" }, filter: {},
        sorts: { type: "array", items: { type: "object", properties: { property: { type: "string", enum: ["created_at", "updated_at"] }, direction: { type: "string", enum: ["ascending", "descending"] } }, required: ["property", "direction"], additionalProperties: false } },
        start_cursor: { type: "string" }, page_size: { type: "integer", minimum: 1, maximum: 100, default: 100 },
      },
      additionalProperties: false,
    },
  },
  {
    name: "notion-search-sessions",
    title: "Search Notion agent sessions",
    description: "Search indexed past Custom Agent sessions by topic and return session URLs and excerpts.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: { type: "object", properties: { query: { type: "string", minLength: 1 } }, required: ["query"], additionalProperties: false },
  },
  {
    name: "notion-spawn-session",
    title: "Start a Notion Custom Agent session",
    description: "Start a session with one published Custom Agent and send its first message.",
    annotations: writeAnnotations,
    inputSchema: { type: "object", properties: { agent_url: { type: "string", minLength: 1 }, message: { type: "string", minLength: 1 } }, required: ["agent_url", "message"], additionalProperties: false },
  },
  {
    name: "notion-get-session-status",
    title: "Get Notion agent session status",
    description: "Get the latest turn state for one accessible Custom Agent session without waiting.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 } }, required: ["session_id"], additionalProperties: false },
  },
  {
    name: "notion-wait-session",
    title: "Wait for a Notion agent session",
    description: "Wait for the latest Custom Agent turn to reach a stable state.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: false, openWorldHint: false },
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 } }, required: ["session_id"], additionalProperties: false },
  },
  {
    name: "notion-stop-session",
    title: "Stop a Notion agent session",
    description: "Stop the active turn in one accessible Custom Agent session.",
    annotations: updateAnnotations,
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 } }, required: ["session_id"], additionalProperties: false },
  },
  {
    name: "notion-send-message-to-session",
    title: "Send a Notion agent session message",
    description: "Send a follow-up message to one accessible Custom Agent session.",
    annotations: writeAnnotations,
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 }, message: { type: "string", minLength: 1 } }, required: ["session_id", "message"], additionalProperties: false },
  },
  {
    name: "notion-list-session-events",
    title: "List Notion agent session events",
    description: "List short summaries of saved events in one Custom Agent session.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 }, start_cursor: { type: "string" }, page_size: { type: "integer", minimum: 1, maximum: 100, default: 100 } }, required: ["session_id"], additionalProperties: false },
  },
  {
    name: "notion-read-session-event",
    title: "Read a Notion agent session event",
    description: "Read the complete visible content of one saved Custom Agent session event.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: { type: "object", properties: { session_id: { type: "string", minLength: 1 }, event_id: { type: "string", minLength: 1 } }, required: ["session_id", "event_id"], additionalProperties: false },
  },
  {
    name: "notion-create-comment",
    title: "Create a Notion comment",
    description: "Add a page-level comment, comment on selected content, or reply to an existing discussion.",
    annotations: writeAnnotations,
    inputSchema: {
      type: "object",
      properties: {
        page_id: { type: "string", minLength: 1 },
        discussion_id: { type: "string", minLength: 1 },
        selection_with_ellipsis: { type: "string", minLength: 1 },
        markdown: { type: "string", minLength: 1 },
        rich_text: { type: "array", minItems: 1, items: { type: "object", additionalProperties: true } },
      },
      required: ["page_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-get-comments",
    title: "Get Notion comments",
    description: "Get page discussions, with optional child-block, resolved-thread, or single-discussion selection.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: {
        page_id: { type: "string", minLength: 1 },
        discussion_id: { type: "string", minLength: 1 },
        include_all_blocks: { type: "boolean", default: false },
        include_resolved: { type: "boolean", default: false },
      },
      required: ["page_id"],
      additionalProperties: false,
    },
  },
  {
    name: "notion-get-async-task",
    title: "Get a Notion async task",
    description: "Get the state and result or error of a page write task.",
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: "object",
      properties: { task_id: { type: "string", minLength: 1 } },
      required: ["task_id"],
      additionalProperties: false,
    },
  },
];

export function toolsForClient(clientName = "") {
  if (!/(openai|chatgpt|codex)/i.test(clientName)) return structuredClone(notionMcpTools);
  return notionMcpTools.map((tool) => ({
    ...structuredClone(tool),
    name: tool.name === "notion-search" ? "search" : tool.name === "notion-fetch" ? "fetch" : tool.name,
  }));
}
